/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: ['selector', '[data-theme="dark"]'],
  theme: {
    extend: {
      colors: {
        paper: '#F4F6F8',
        paperDeep: '#E9EDF1',
        ink: '#0F172A',
        inkSoft: '#475569',
        inkFaint: '#94A3B8',
        rule: '#E2E8F0',
        ruleStrong: '#0F172A',
        verified: '#15803D',
        verifiedBg: '#DCFCE7',
        attention: '#B45309',
        attentionBg: '#FEF3C7',
        problem: '#B91C1C',
        problemBg: '#FEE2E2',
        accent: '#1D4ED8',
        accentSoft: '#DBEAFE',

        dpaper: '#0B1220',
        dpaperDeep: '#070C16',
        dink: '#F1F5F9',
        dinkSoft: '#B6C2D2',
        dinkFaint: '#64748B',
        drule: '#1E293B',
        druleStrong: '#F1F5F9',
        dverified: '#4ADE80',
        dverifiedBg: '#052E16',
        dattention: '#FBBF24',
        dattentionBg: '#451A03',
        dproblem: '#F87171',
        dproblemBg: '#450A0A',
        daccent: '#93C5FD',
        daccentSoft: '#172554',
      },
      fontFamily: {
        serif: ['"Inter"', 'sans-serif'],
        sans: ['"Inter"', 'sans-serif'],
        mono: ['"Inter"', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
