export function initialState() {
  return {
    available: 18200,
    user: { phone: '0803 123 4567', relayId: 'B-0421', pinSet: true, role: 'user', name: 'Bello' },
    business: { name: '', rc: '', type: 'employer', verified: false },
    workers: [
      { id: 'w1', name: 'Adaeze O.', phone: '0803 111 2222', email: 'adaeze@example.com', salary: 250000 },
      { id: 'w2', name: 'Chidi M.', phone: '0803 333 4444', email: 'chidi@example.com', salary: 180000 },
    ],
    escrows: [],
    requests: [
      { id: 'rq1', kind: 'trusted', issuerType: 'employer', issuerName: 'Aethercode Ltd', to: 'Adaeze O.', phone: '0803 111 2222', email: 'adaeze@example.com', amount: 250000, settlement: 'Sept 30', note: 'Sept salary', status: 'pending', created: 'now' },
    ],
    lpPortfolio: [],
    notifications: [
      { id: 'n1', text: 'Promise #8472 verified — ₦5,000 spendable now', time: 'now' },
      { id: 'n2', text: 'Salary promise verified — settles Sept 30', time: '2h' },
    ],
    promises: [
      {
        id: 'p-salary',
        amount: 25000,
        remaining: 25000,
        from: 'Employer — Aethercode Ltd',
        to: 'You',
        label: 'Salary',
        settlement: 'Settles Sept 30',
        status: 'verified',
        spendable: true,
        health: 'healthy',
        kind: 'trusted',
        pendingAccept: false,
      },
      {
        id: 'p-8472',
        amount: 5000,
        remaining: 5000,
        from: 'A',
        to: 'You',
        label: 'From A',
        settlement: 'Network is down — settling when it returns',
        status: 'verified',
        spendable: true,
        health: 'healthy',
        kind: 'in-transit',
        chain: { root: 'A', edges: [] },
        pendingAccept: false,
      },
      {
        id: 'p-refund',
        amount: 2000,
        remaining: 2000,
        from: 'Merchant refund',
        to: 'You',
        label: 'Refund',
        settlement: 'Settles tomorrow',
        status: 'verified',
        spendable: true,
        health: 'attention',
        kind: 'escrow',
        pendingAccept: true,
      },
    ],
    transactions: [],
    externalBids: [],
    payerPromises: [
      { id: 'pp1', amount: 150000, to: 'B', settlement: 'Sept 30', status: 'verified', kind: 'trusted' },
      { id: 'pp2', amount: 80000, to: 'C', settlement: 'Sept 28', status: 'verified', kind: 'in-transit' },
    ],
  }
}
